### ISSUE TITLE
IAM role in README should also indicate start instance.

### ISSUE THREAD

**Issue by kdbanman** [andrewmclagan/aws-lambda-ec2-start-stop#1]
I just used this in a pair of lambda functions to start and stop a game server.  Works great!  I don't have experience with lambda either.

Anyways, I'm pretty sure that the IAM role document example in the readme should be allowed to start instances.  See commented line below and let me know if I misunderstand.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "MyStatementId",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:StopInstances",
                "ec2:StartInstances"     /// <-- Include this in your README?
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by andrewmclagan** [comment]
Ah yes can you please make a PR and I will merge it. Thanks :)
